language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
